[project]
name = "automate-boring-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
]

[tool.uv.workspace]
members = [
    "guess",
    "rock_paper_scissors",
]
